export enum HikeName {
  CoryPass = "Cory Pass",
  SulphurMountain = "Sulphur Mountain",
  TunnelMountain = "Tunnel Mountain",
  MountJacquesCartier = "Mount Jacques Cartier",
  MountAlbert = "Mount Albert",
  MamquamFalls = "Mamquam Falls",
  StawamusChief = "Stawamus Chief",
  PathOfLemons = "Path of Lemons",
  PathOfTheGods = "Path of the Gods",
  MountGiant = "Mount Giant",
  AlgonquinPeak = "Algonquin Peak",
  JayMountain = "Jay Mountain",
  MountMansfield = "Mount Mansfield",
}
