name: Build and Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build static files and commit to build branch for deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: hitched-hikers/hitched-hikers.github.io
          ref: main
          token: ${{ secrets.PAT }}
      - name: Set-up Node
        uses: actions/setup-node@v3
      - run: npm install -g bun
      - run: bun install
      - run: 'echo "$MAPBOX_ACCESS_TOKEN" > src/Utils/MapboxAccessToken.txt'
        shell: bash
        env:
          MAPBOX_ACCESS_TOKEN: ${{secrets.MAPBOX_ACCESS_TOKEN}}
      - run: bun build-app
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.PAT }}
          MESSAGE: "Build: ({sha}) {msg}"
